on: [push]

jobs:
  test_run:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker
        uses: ./ # Uses an action in the root directory
        with:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - run: docker pull alpine
      - run: docker tag alpine ${{ secrets.DOCKER_TEST_TAG }}
      - run: docker push ${{ secrets.DOCKER_TEST_TAG }}